Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end  
    config.vm.box = "ubuntu/focal64"
    # Install a private network, so that VMs can connect to each other.
    config.vm.network "private_network", type: "dhcp"
    config.vm.provision "shell", path: "bootstrap.sh"    
end
  