apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greetings-app
  name: greetings-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greetings-app
  template:
    metadata:
      labels:
        app: greetings-app
    spec:
      containers:
      - image: sandeepmaurya/springboot
        name: springboot
        ports:
        - containerPort: 8080
