Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    config.vm.box = "ubuntu/focal64"
    # Install a private network, so that VMs can connect to each other.
    config.vm.network "private_network", type: "dhcp"
    config.vm.provision "shell", path: "bootstrap.sh"
  
    config.vm.define "control-plane" do |c|
      c.vm.hostname = "control-plane"
    end
  
    config.vm.define "worker1" do |w1|
      w1.vm.hostname = "worker1"
    end
  
    config.vm.define "worker2" do |w2|
      w2.vm.hostname = "worker2"
    end
  
  end
  